name: Spring Boot CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew clean build

      - name:
          확인: JAR 생성 여부
        run: |
          ./gradlew bootJar
          find . -name "*.jar"

      - name: Copy JAR and yml to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: build/libs/auth-0.0.1-SNAPSHOT.jar
          target: /home/ec2-user/app

      - name: SSH to EC2 and restart server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ec2-user/app
            PID=$(lsof -ti :8080)
            if [ -n "$PID" ]; then
              kill -9 $PID
            fi
            nohup java -jar *.jar --server.port=8080 > log.txt 2>&1 &