name: Spring Boot CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Get execution permission to gradlew
        run: chmod +x ./gradle

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Find JARs (debug)
        run: find . -name "*.jar"

      - name: Copy JAR and yml to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: build/libs/project_BE-0.0.1-SNAPSHOT.jar
          target: /home/ec2-user/app

      - name: SSH to EC2 and restart server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ec2-user/app
          
            echo "현재 실행 중인 서버 종료 시도..."
                  PID=$(lsof -ti :8080)
                  if [ -n "$PID" ]; then
                    echo "기존 서버(PID: $PID) 종료"
                    kill -9 $PID
                  else
                    echo "기존 서버 없음"
                  fi

                  echo "실행 가능한 JAR 확인:"
                  ls -al *.jar || { echo "JAR 파일 없음"; exit 1; }

                  echo "서버 재실행"
                  nohup java -jar *.jar --server.port=8080 > log.txt 2>&1 &

                  sleep 5
                  if lsof -i :8080; then
                    echo "서버 실행 성공”
                  else
                    echo "서버 실행 실패"
                    exit 1
                  fi